services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - ../haproxy.tech/config/haproxy.tech.conf:/config/haproxy.tech/haproxy.tech.conf
      - ../haproxy.tech/config/ssl:/data/haproxy.tech/ssl
      - ../haproxy.tech/www:/srv/haproxy.tech/www
      - ../bibica.net/config/bibica.net.conf:/config/bibica.net/bibica.net.conf
      - ../bibica.net/config/ssl:/data/bibica.net/ssl
      - ../bibica.net/www:/srv/bibica.net/www
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      
networks:
  reverse_proxy:
    driver: "bridge"
    name: reverse_proxy